# Generated by Django 5.2.4 on 2025-07-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryConfiguration",
            fields=[
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.repository",
                    ),
                ),
                (
                    "main_branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
