# Generated by Django 5.2.4 on 2025-07-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_repositoryconfiguration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositoryconfiguration",
            name="main_branch_name",
        ),
        migrations.AddField(
            model_name="repositoryconfiguration",
            name="main_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.branch",
            ),
        ),
    ]
