# Generated by Django 5.2.4 on 2025-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_repositoryconfiguration_main_branch_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryconfiguration",
            name="pr_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the generated Pull Request",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="repositoryconfiguration",
            name="process_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for the flowchart generation process",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="repositoryconfiguration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CLONING", "Cloning Repository"),
                    ("PROCESSING", "Processing Files"),
                    ("GENERATING_MD", "Generating README.md"),
                    ("PUSHING", "Pushing to GitHub"),
                    ("PR_CREATED", "Pull Request Created"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("STOPPED", "Stopped"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
